/**************BLOQUE ANONIMO PARA LOS PROCEDIMIENTO ALMACENADOS***************/
--1.-    /*==============TABLA TIPO_CATEGORIA==============*/
/*==============LLAMADA AL PROCEDIMIENTO==============*/
DECLARE     
BEGIN
       PA_INSERTAR_TIPO_CATEGORIA(1,'3 ESTRELLA');
END;
/

--2.-       /*===========TABLA HOTEL===================*/
/*=============LLAMADA AL PROCEDIMIENTO================*/
DECLARE     
BEGIN
       PA_INSERTAR_HOTEL(1,1,'PACIFICO','MANTA',0947238249);
END;
/

--3.-     /*==============TABLA CLIENTE==============*/
/*=================LLAMADA AL PROCEDIMIENTO=============*/
DECLARE     
BEGIN
       PA_INSERTAR_CLIENTE(1, 'DIEGO','SANTANA', 1315227728, 'CALLE 12 AV 34', 'MANTA', 25);
END;
/

--4.-      /*==============TABLA RESERVACION===========*/
/*=================LLAMADA AL PROCEDIMIENTO============*/
DECLARE     
BEGIN
       PA_INSERTAR_RESERVACION(2,1,3,0,'12/07/2017','17/07/2017');
END;
/

--5.-     /*==========TABLA TIPO_PAGO==============*/
/*==============LLAMADA AL PROCEDIMIENTO==============*/
DECLARE     
BEGIN
        PA_INSERTAR_TIPO_PAGO(1,'TARJETA');
      --PA_INSERTAR_TIPO_PAGO(2,'EFECTIVO');
END;
/

--6.-      /*==============TABLA FACTURA==============*/
/*==============LLAMADA AL PROCEDIMIENTO==============*/
DECLARE     
BEGIN
       PA_INSERTAR_FACTURA(1,1,1,0,NULL,0);
END;
/

--7.-    /*==============TABLA HABITACION==============*/
/*==============LLAMADA AL PROCEDIMIENTO===============*/
DECLARE     
BEGIN
       PA_INSERTAR_HABITACION(1,1,1,'PRESIDENCIAL', 35, 'OCUPADO');
END;
/

--8.-   /*===ELIMINAR REGISTROS DE TODAS LAS TABLAS=====*/
/*===============LLAMADA AL PROCEDIMIENTO===============*/
DECLARE     
BEGIN
       PA_ELIMINAR_REGISTROS;
END;
/

--9.-  /*====ELIMINAR REGISTRO DE LA TABLA FACTURA===*/
 /*===============LLAMADA AL PROCEDIMIENTO==============*/
DECLARE     
BEGIN
       PA_ELIMINAR_FACTURA;
       
END;
/

--10.-  /*====ACTUALIZAR DIRECCION DE LA TABLA CLIENTE===*/
/*=================LLAMADA AL PROCEDIMIENTO=============*/
DECLARE     
BEGIN
       PA_ACTUALIZAR_DIRE_CLIENTE(1,'CALLE 15 AV 20');
END;
/

/*******************************BLOQUE ANONIMO PARA LOS TRIGGER***************************/

--11.-  /*====TRIGGER QUE PROHIBE QUE SE INGRESE NUMEROS MAYORES A 10 EN EL CAMPO TELEFONO===*/
/*=================LLAMADA AL PROCEDIMIENTO=============*/
DECLARE     
BEGIN
       PA_INSERTAR_HOTEL(2,1,'ORO VERDE','MANTA',094723824318);
END;
/

--12.-  /*====TRIGGER QUE PERMITA SOLO INGRESAR LOS SIGUIENTES CARACTERES 'PRESIDENCIAL, 'PERSONAL. 'MATRIMONIAL','FAMILIAR'===*/
/*=================LLAMADA AL PROCEDIMIENTO=============*/
DECLARE     
BEGIN
       PA_INSERTAR_HABITACION(1,1,1,'PRESIDENCIAAL', 35, 'OCUPADO');
       PA_INSERTAR_HABITACION(1,1,1,'PERSONAAL', 35, 'OCUPADO');
       PA_INSERTAR_HABITACION(1,1,1,'FAMILIAAR', 35, 'OCUPADO');
       PA_INSERTAR_HABITACION(1,1,1,'MATRIMONIAAL', 35, 'OCUPADO');
END;
/

--13.-  /*====TRIGGER QUE PERMITA SOLO INGRESAR LOS SIGUIENTES CARACTERES '1 ESTRELLA',*/
      /*'2 ESTRELLA', '3 ESTRELLA', '4 ESTRELLA', '5 ESTRELLA' EN EL CANMPO DESCRIPCION===*/
/*=================LLAMADA AL PROCEDIMIENTO=============*/
DECLARE     
BEGIN
       PA_INSERTAR_TIPO_CATEGORIA(1,'1 ESTRELLAA');
       PA_INSERTAR_TIPO_CATEGORIA(2,'2 ESTRELLAA');
       PA_INSERTAR_TIPO_CATEGORIA(3,'3 ESTRELLAA');
       PA_INSERTAR_TIPO_CATEGORIA(4,'4 ESTRELLAA');
       PA_INSERTAR_TIPO_CATEGORIA(5,'5 ESTRELLAA');
END;
/

--14.-  /*====TRIGGER QUE PERMITA INGRESAR SOLO 10 DIGITOS EN EL CAMPO CEDULA===*/
/*=================LLAMADA AL PROCEDIMIENTO=============*/
DECLARE     
BEGIN
       PA_INSERTAR_CLIENTE(1,1,'DIEGO','SANTANA',13152277281,'CALLE 12 AV 34','MANTA',20);
END;
/

--15.-  /*====TRIGGER QUE PERMITA INGRESAR SOLO TIPO_PAGO EN DESCRIPCION 'EFECTIVO' O 'TARJETA'===*/
/*=================LLAMADA AL PROCEDIMIENTO=============*/
DECLARE     
BEGIN
        PA_INSERTAR_TIPO_PAGO(1,'TARJETAA');
        PA_INSERTAR_TIPO_PAGO(2,'EFECTIVOO');
END;
/

--16.-  /*====TRIGGER QUE ACTUALICE EL PRECIO DEPENDIENTO DEL TIPO DE HABITACION QUE COLOQUEMOS===*/
/*=================LLAMADA AL PROCEDIMIENTO=============*/
DECLARE     
BEGIN
       PA_INSERTAR_RESERVACION(1,1,3,0,'12/07/2017','17/07/2017');
       PA_INSERTAR_RESERVACION(2,1,3,0,'12/07/2017','20/07/2017');
       PA_INSERTAR_TIPO_PAGO(1,'TARJETA');
       PA_INSERTAR_FACTURA(1,1,1,0,NULL, 0);
       PA_INSERTAR_HABITACION(1,1,1,'PRESIDENCIAL', 35, 'OCUPADO');
END;
/

--17.-  /*====TRIGGER QUE ACTUALICE EL CAMPO FECHA DE LA TABLA FACTURA DEPENDIENDO DE LA FECHA_FIN QUE CONTIENE LA TABLA RESERVACION  ===*/
/*=================LLAMADA AL PROCEDIMIENTO=============*/
DECLARE     
BEGIN
     
       PA_INSERTAR_RESERVACION(1,1,3,0,'12/07/2017','17/07/2017');
       PA_INSERTAR_RESERVACION(2,1,3,0,'12/07/2017','20/07/2017');
       PA_INSERTAR_TIPO_PAGO(1,'TARJETA');
       PA_INSERTAR_FACTURA(1,1,1,0,NULL, 0);
       PA_INSERTAR_HABITACION(1,1,1,'PRESIDENCIAL', 35, 'OCUPADO');
END;
/

--18.-  /*====TRIIGER QUE ACTUALICE El campo total DE LA TABLA FACTURA, multiplicando el precio por cantidad_reservacion de la tabla reservacion===*/
/*=================LLAMADA AL PROCEDIMIENTO=============*/
DECLARE     
BEGIN
       PA_INSERTAR_RESERVACION(1,1,3,0,'12/07/2017','17/07/2017');
       PA_INSERTAR_RESERVACION(2,1,3,0,'12/07/2017','20/07/2017');
       PA_INSERTAR_TIPO_PAGO(1,'TARJETA');
       PA_INSERTAR_FACTURA(1,1,1,0,NULL, 0);
       PA_INSERTAR_HABITACION(1,1,1,'PRESIDENCIAL', 35, 'OCUPADO');
END;
/

--19.-  /*====trigger que me actualice el campo total, en funcion del descuento con la condicion, si el cliente tiene mas de 2 reservaciones===*/
/*=================LLAMADA AL PROCEDIMIENTO=============*/
DECLARE     
BEGIN
     
       PA_INSERTAR_RESERVACION(1,1,3,0,'12/07/2017','17/07/2017');
       PA_INSERTAR_RESERVACION(2,1,3,0,'12/07/2017','20/07/2017');
       PA_INSERTAR_TIPO_PAGO(1,'TARJETA');
       PA_INSERTAR_FACTURA(1,1,1,0,NULL, 0);
       PA_INSERTAR_HABITACION(1,1,1,'PRESIDENCIAL', 35, 'OCUPADO');
END;
/

--20--
DECLARE     
BEGIN
       PA_INSERTAR_CLIENTE(2, 'DIEGO','SANTANA', 1315227728, 'CALLE 12 AV 34', 'MANTA', 17);
END;
/