/*ver registros en la tablas*/
  SELECT * FROM TIPO_CATEGORIA;
  SELECT * FROM HOTEL;
  SELECT * FROM CLIENTE;
  SELECT * FROM RESERVACION;
  SELECT * FROM TIPO_PAGO;
  SELECT * FROM FACTURA;
  SELECT * FROM HABITACION;

/*eliminar registros en la tablas*/
  DELETE FROM HABITACION;
  DELETE FROM FACTURA;
  DELETE FROM TIPO_PAGO;
  DELETE FROM RESERVACION;
  DELETE FROM CLIENTE;
  DELETE FROM HOTEL;
  DELETE FROM TIPO_CATEGORIA;

